#!/bin/sh

_base_url='https://aur.archlinux.org/cgit/aur.git/snapshot'

get_url_function() {
  _pkg="$1"
  _url="${_base_url}/${_pkg}.tar.gz"

  echo "$_url"
}

run_wgetpkg_function() {
  _pkg="$(echo "$1" | tr -d '[:space:]')"
  _url="$(get_url_function "$_pkg")"

  wget --no-verbose "$_url"
}

wgetpkg_function() {
  for _pkg in "$@"; do
    run_wgetpkg_function "$_pkg" &
  done
  wait
}

usage_function() {
  cat <<EOF
Usage:
  wgetpkg [-h|--help]
  wgetpkg <pkg> <pkg>...

Options:
  -h, --help
    print this help message
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    -*)
      usage_function
      exit 0
      ;;
    *)
      wgetpkg_function "$@"
      exit 0
      ;;
  esac
done

# vim: set filetype=sh foldmethod=marker foldlevel=0:
